title: Renuka Phandey # your name (or website title) here
logo: "/images/profile.png?raw=true" <br><br> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  5+ years of Software Development experience.  Possess Bachelor of Science Degree in Computer Science from Aston University. 
  <br><br>
  Currently working as a Salesforce Developer with strong knowledge and experience in Apex Classes, Triggers, Lightning Components as well as syncing data from Salesforce to Heroku.
  <br><br> 
  
theme: jekyll-theme-minimal
